### ISSUE TITLE
After update SearXNG no longer works (nginx 504 Gateway time-out)

### ISSUE THREAD

**Issue by pepecyb** [YunoHost-Apps/searxng_ynh#261]
### Description of my issue

After updating from version `2024.04.26.21.42.29~ynh1` to version `2024.05.10.13.42.17~ynh1`, SearXNG no longer works. When calling the app, an error page (nginx) 504 Gateway Time-out appears after some time.

### Context

- Hardware: *VPS bought online*
- YunoHost version: *11.2.11.3 (stable)*
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *`2024.05.10.13.42.17~ynh1`*
- If upgrading, current package version: *`2024.05.10.13.42.17~ynh1`*

### Logs

`2024/05/13 19:13:53 [error] 857330#857330: *1436910 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 84.224.205.239, server: searx.pericles.hu, request: "GET / HTTP/2.0", upstream: "uwsgi://unix:///var/run/searxng/app.socket", host: "searx.pericles.hu"`

**Comment by Graninius** [comment]
Have the same issue.

**Comment by kamazeuci** [comment]
same issue here. And a buch of processes uwsgi or asyncio_loop by user searxng take the whole CPU of the server.

**Comment by kamazeuci** [comment]
![image](https://github.com/YunoHost-Apps/searxng_ynh/assets/26315958/1357171b-0f11-4c7d-8e4e-685426d4ec9e)

**Comment by kamazeuci** [comment]
`File "/var/www/searxng/searxng-src/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
  File "/var/www/searxng/searxng-src/searx/utils.py", line 428, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/searxng/searxng-src/searx/engines/google_play_apps.py'
2024-05-18 18:03:17,267 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,272 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,280 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,283 ERROR:searx.engines: Cannot load engine "google_play_apps"
Traceback (most recent call last):
  File "/var/www/searxng/searxng-src/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
  File "/var/www/searxng/searxng-src/searx/utils.py", line 428, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/searxng/searxng-src/searx/engines/google_play_apps.py'
2024-05-18 18:03:17,290 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,294 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,303 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,343 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,351 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,356 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,364 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,432 ERROR:searx.engines: Cannot load engine "duckduckgo_images"
Traceback (most recent call last):
  File "/var/www/searxng/searxng-src/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
  File "/var/www/searxng/searxng-src/searx/utils.py", line 428, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/searxng/searxng-src/searx/engines/duckduckgo_images.py'
2024-05-18 18:03:17,461 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv
2024-05-18 18:03:17,472 ERROR:searx.engines: Cannot load engine "google_play_apps"
Traceback (most recent call last):
  File "/var/www/searxng/searxng-src/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
  File "/var/www/searxng/searxng-src/searx/utils.py", line 428, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/searxng/searxng-src/searx/engines/google_play_apps.py'
2024-05-18 18:03:17,594 ERROR:searx.engines: Engine config error: ambiguous shortcut: c3tv`

**Comment by pepecyb** [comment]
There seems to be a problem with the configuration file of the previous version. Following a tip, I completely uninstalled SearxNG and then reinstalled it. The problem has been solved and the application works again without errors.

**Comment by kamazeuci** [comment]
yes! done (uninstalled and installed again) and now it works. Don't know if I lost my config though.

**Comment by Graninius** [comment]
Yes, it works after clean install.
